export const randomModuleLesson = {
  title: "random Module",
  slug: "random-module",
  content: `# random Module

The \`random\` module generates pseudo-random numbers for simulations, games, testing, and statistical sampling. Pseudo-random means the numbers appear random but are generated by a deterministic algorithm.

\`\`\`python
import random
\`\`\`

## random() - Random Float Between 0 and 1

\`random.random()\` returns a float in the range \`[0.0, 1.0)\` - includes 0 but not 1.

\`\`\`python
import random

print(random.random())   # e.g. 0.7234561289
print(random.random())   # e.g. 0.1823456789
print(random.random())   # e.g. 0.9012345678

# Scale to any range [a, b)
a, b = 10, 20
scaled = a + (b - a) * random.random()
print(scaled)   # e.g. 14.7234...

# Probability check (30% chance)
if random.random() < 0.30:
    print("Event occurred (30% probability)")
\`\`\`

### uniform() - Random Float in a Range

\`\`\`python
import random

# random float between 1.5 and 3.5
print(random.uniform(1.5, 3.5))   # e.g. 2.783...
print(random.uniform(0, 100))     # e.g. 67.42...
print(random.uniform(-5, 5))      # e.g. -2.14...

# Simulate temperature readings
temps = [round(random.uniform(35.5, 38.5), 1) for _ in range(5)]
print(temps)   # e.g. [36.2, 37.8, 36.9, 38.1, 37.3]
\`\`\`

## randint() - Random Integer in a Range

\`random.randint(a, b)\` returns a random integer where \`a <= N <= b\` (BOTH ends inclusive).

\`\`\`python
import random

# Both a and b are included!
print(random.randint(1, 6))    # Simulates a dice: 1, 2, 3, 4, 5, or 6
print(random.randint(0, 1))    # Simulates a coin: 0 or 1
print(random.randint(1, 100))  # Random number 1-100

# Roll dice 10 times
rolls = [random.randint(1, 6) for _ in range(10)]
print(rolls)   # e.g. [3, 1, 6, 2, 4, 6, 1, 3, 5, 2]
print(f"Average roll: {sum(rolls)/len(rolls):.2f}")
\`\`\`

### randrange() - Random from Range with Step

\`\`\`python
import random

# random.randrange(start, stop, step) - same as random.choice(range(...))
print(random.randrange(0, 10))        # 0-9 (stop not included!)
print(random.randrange(0, 10, 2))     # 0, 2, 4, 6, or 8 (even only)
print(random.randrange(1, 10, 2))     # 1, 3, 5, 7, or 9 (odd only)
print(random.randrange(0, 101, 5))    # Multiples of 5: 0,5,10,...,100
\`\`\`

## choice() - Pick One Random Item

\`random.choice(sequence)\` picks one item from a non-empty sequence.

\`\`\`python
import random

fruits = ["apple", "banana", "cherry", "mango", "grape"]
print(random.choice(fruits))   # e.g. "cherry"
print(random.choice(fruits))   # e.g. "apple"

# Roll a dice
sides = [1, 2, 3, 4, 5, 6]
print(random.choice(sides))    # e.g. 4

# Flip a coin
coin = random.choice(["Heads", "Tails"])
print(coin)

# Choose from a string (picks a character)
print(random.choice("Python"))   # e.g. 't'

# Random direction
directions = ["North", "South", "East", "West"]
print(random.choice(directions))

# Error on empty sequence
# random.choice([])   # IndexError: Cannot choose from an empty sequence
\`\`\`

### choices() - Pick Multiple with Replacement

\`\`\`python
import random

fruits = ["apple", "banana", "cherry"]

# Pick 3 with replacement (same item can appear multiple times)
print(random.choices(fruits, k=3))   # e.g. ['banana', 'banana', 'apple']

# With weights (cherry 3x more likely than others)
weighted = random.choices(fruits, weights=[1, 1, 3], k=10)
print(weighted.count("cherry"))   # Usually around 6

# Simulating a loaded die
die = [1, 2, 3, 4, 5, 6]
weights = [1, 1, 1, 1, 1, 3]   # 6 is 3x more likely
rolls = random.choices(die, weights=weights, k=100)
print(f"Got 6: {rolls.count(6)} times out of 100")
\`\`\`

## shuffle() - Randomly Reorder a List

\`random.shuffle(list)\` shuffles a list **in-place** (modifies the original).

\`\`\`python
import random

cards = list(range(1, 14))   # Cards 1-13
print("Before:", cards)

random.shuffle(cards)
print("After: ", cards)   # e.g. [7, 2, 11, 1, 9, 4, 13, 6, 3, 12, 8, 5, 10]

# Shuffle returns None - common mistake!
deck = list(range(52))
result = random.shuffle(deck)
print(result)    # None  (NOT the shuffled list!)
print(deck[:5])  # The deck itself is shuffled

# To shuffle and keep original
import copy
original = [1, 2, 3, 4, 5]
shuffled = original.copy()
random.shuffle(shuffled)
print("Original:", original)   # [1, 2, 3, 4, 5]  (unchanged)
print("Shuffled:", shuffled)   # e.g. [3, 1, 5, 2, 4]

# Practical: create teams
students = ["Alice", "Bob", "Charlie", "Diana", "Eve", "Frank"]
random.shuffle(students)
team1 = students[:3]
team2 = students[3:]
print(f"Team 1: {team1}")
print(f"Team 2: {team2}")
\`\`\`

## sample() - Pick Multiple Without Replacement

\`random.sample(population, k)\` picks k unique items - no item is chosen twice.

\`\`\`python
import random

numbers = list(range(1, 50))

# Pick 6 unique numbers (like a lottery)
lottery = random.sample(numbers, 6)
lottery.sort()
print(f"Lottery numbers: {lottery}")   # e.g. [5, 12, 23, 31, 38, 45]

# Pick 3 winners from participants
participants = ["Alice", "Bob", "Charlie", "Diana", "Eve", "Frank"]
winners = random.sample(participants, 3)
print(f"Winners: {winners}")

# Sample from a string
word = "Python"
letters = random.sample(word, 4)
print(letters)   # e.g. ['h', 'P', 'n', 'o']

# Error: k cannot exceed population size
# random.sample([1, 2, 3], 5)   # ValueError!
\`\`\`

### sample() vs choices() vs shuffle()

\`\`\`
Function       Replacement    Modifies original    Returns
-----------    -----------    -----------------    ----------
sample(p, k)   NO             No                   New list
choices(p, k)  YES            No                   New list
shuffle(p)     N/A            YES                  None
\`\`\`

## seed() - Make Random Numbers Reproducible

\`random.seed()\` initializes the random number generator. Using the same seed produces the same sequence every time - essential for testing and reproducibility.

\`\`\`python
import random

# Without seed - different every run
print(random.random())   # e.g. 0.7234...
print(random.random())   # e.g. 0.1823...

# With seed - same sequence every time
random.seed(42)
print(random.random())   # Always 0.6394267984578837
print(random.random())   # Always 0.025010755222666936

# Run again with same seed
random.seed(42)
print(random.random())   # Same: 0.6394267984578837
print(random.random())   # Same: 0.025010755222666936

# Seed with current time (default behavior when no seed given)
import time
random.seed(int(time.time()))

# Practical: reproducible experiment
def run_experiment(seed_value):
    random.seed(seed_value)
    results = [random.randint(1, 100) for _ in range(5)]
    return results

print(run_experiment(123))   # Always the same 5 numbers
print(run_experiment(123))   # Identical output
print(run_experiment(456))   # Different numbers (different seed)
\`\`\`

## Other Useful Functions

\`\`\`python
import random

# gauss(mu, sigma) - Gaussian (normal) distribution
heights = [random.gauss(170, 10) for _ in range(5)]
print([round(h, 1) for h in heights])   # e.g. [165.3, 178.2, 169.7, 155.4, 172.1]

# triangular(low, high, mode) - triangular distribution
score = random.triangular(0, 100, 75)   # Most likely around 75
print(round(score, 1))

# betavariate, expovariate for statistical distributions
\`\`\`

## Practical Example: Card Game Simulator

\`\`\`python
import random

def create_deck():
    suits = ["Hearts", "Diamonds", "Clubs", "Spades"]
    ranks = ["2","3","4","5","6","7","8","9","10","J","Q","K","A"]
    return [(rank, suit) for suit in suits for rank in ranks]

def card_value(card):
    rank = card[0]
    if rank in ["J", "Q", "K"]:
        return 10
    elif rank == "A":
        return 11
    else:
        return int(rank)

def hand_value(hand):
    total = sum(card_value(c) for c in hand)
    aces = sum(1 for c in hand if c[0] == "A")
    while total > 21 and aces:
        total -= 10
        aces -= 1
    return total

def format_hand(hand):
    return ", ".join(f"{r} of {s}" for r, s in hand)

random.seed(42)   # For reproducible demo

deck = create_deck()
random.shuffle(deck)

# Deal two hands
player_hand = [deck.pop(), deck.pop()]
dealer_hand = [deck.pop(), deck.pop()]

print("=== Blackjack ===")
print(f"Player: {format_hand(player_hand)} = {hand_value(player_hand)}")
print(f"Dealer: {dealer_hand[0][0]} of {dealer_hand[0][1]} + [hidden]")

# Player hits until 17+
while hand_value(player_hand) < 17:
    player_hand.append(deck.pop())
    print(f"Player hits: {format_hand(player_hand)} = {hand_value(player_hand)}")

# Dealer reveals
print(f"Dealer reveals: {format_hand(dealer_hand)} = {hand_value(dealer_hand)}")
while hand_value(dealer_hand) < 17:
    dealer_hand.append(deck.pop())
    print(f"Dealer hits: {format_hand(dealer_hand)} = {hand_value(dealer_hand)}")

p_val = hand_value(player_hand)
d_val = hand_value(dealer_hand)

if p_val > 21:
    print("Player busts! Dealer wins.")
elif d_val > 21:
    print("Dealer busts! Player wins.")
elif p_val > d_val:
    print(f"Player wins! ({p_val} vs {d_val})")
elif d_val > p_val:
    print(f"Dealer wins! ({d_val} vs {p_val})")
else:
    print(f"Push! Both have {p_val}")
\`\`\`

> [!TIP]
> Use \`random.seed()\` when you need reproducible results (testing, demos, research). Use \`sample()\` when items should not repeat (lottery, teams). Use \`choices()\` when repetition is allowed (simulations). Use \`shuffle()\` to randomize a list in-place, but remember it returns \`None\`, not the shuffled list.`,
  objectives: [
    "Use random() and uniform() to generate random floats.",
    "Use randint() and randrange() to generate random integers.",
    "Use choice(), choices(), sample(), and shuffle() for sequences.",
    "Use seed() to make random sequences reproducible.",
    "Apply the random module in real-world simulations."
  ],
  difficulty: "beginner",
  xpReward: 60,
};